enyo.depends(
  "js/info.js",
  "js/utils.js",
  "js/data.js",
  "js/conf.js",
  "js/urls.js",
  "js/xhr.js",
  "js/storage.js",
  "js/filterList.js",
  "js/menuList.js",
  "js/main.js",
  "css/main.css"
);
